# Generated by Django 2.1.12 on 2019-11-22 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='view',
            name='hit',
        ),
    ]
