# Generated by Django 3.0.2 on 2020-01-25 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20200125_1701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.CharField(blank=True, default='', max_length=200),
            preserve_default=False,
        ),
    ]
