# Generated by Django 2.1.12 on 2019-09-18 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_contactmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('author', models.CharField(max_length=200)),
                ('time_stamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'get_latest_by': 'time_stamp',
            },
        ),
    ]
